version: "3.8"

services:
  backend:
    image: backend:transcendence
    build: ./backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - transcendence

networks:
  transcendence:
    name: "transcendence-network"
    driver: bridge
