version: "3.8"

services:
  backend:
    image: backend:transcendence
    build: ./backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - transcendence

  db:
    image: postgres:16-alpine
    restart: unless-stopped
    networks:
      - transcendence
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB

networks:
  transcendence:
    name: "transcendence-network"
    driver: bridge
