version: "3.8"

services:
  db:
    image: postgres:16-alpine
    container_name: "postgres"
    restart: unless-stopped
    networks:
      - transcendence
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  backend:
    image: backend:transcendence
    container_name: "backend"
    build: ./backend
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - transcendence
    volumes:
      - files:/app/uploads
    environment:
      - APP_NAME
      - BASE_URL=${BACKEND_URL}
      - FRONTEND_URL
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME
      - DB_USERNAME
      - DB_PASSWORD
      - FT_CLIENT_ID
      - FT_CLIENT_SECRET
      - SESSIONS_SECRET
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=PathPrefix(`/api`) || PathPrefix(`/health`) || PathPrefix(`/socket.io`)"
      - "traefik.http.routers.backend.entrypoints=web"

  frontend:
    image: frontend:transcendence
    container_name: "frontend"
    build: ./frontend
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - transcendence
    environment:
      - BASE_URL=${FRONTEND_URL}
      - VITE_BACKEND_URL=${BACKEND_URL}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=PathPrefix(`/`)"
      - "traefik.http.routers.frontend.entrypoints=web"

  traefik:
    image: "traefik:v2.10"
    container_name: "traefik"
    depends_on:
      backend:
        condition: service_healthy
      frontend:
        condition: service_healthy
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    networks:
      - transcendence
    ports:
      - "8000:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

networks:
  transcendence:
    name: "transcendence-network"
    driver: bridge

volumes:
  files:
    name: "transcendence-files"
