version: "3.8"

services:
  db:
    image: postgres:16-alpine
    container_name: "postgres"
    restart: unless-stopped
    networks:
      - transcendence
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  pong:
    image: backend:transcendence
    container_name: "pong"
    build: .
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - transcendence
    ports:
      - 3000:3000
    volumes:
      - files:/app/uploads
    environment:
      - APP_NAME
      - BASE_URL
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME
      - DB_USERNAME
      - DB_PASSWORD
      - FT_CLIENT_ID
      - FT_CLIENT_SECRET
      - SESSIONS_SECRET

networks:
  transcendence:
    name: "transcendence-network"
    driver: bridge

volumes:
  files:
    name: "transcendence-files"
