/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AAvatar: typeof import('./src/components/atoms/AAvatar.vue')['default']
    AButton: typeof import('./src/components/atoms/AButton.vue')['default']
    AButtonIcon: typeof import('./src/components/atoms/AButtonIcon.vue')['default']
    AlertNotification: typeof import('./src/components/AlertNotification.vue')['default']
    ALogo: typeof import('./src/components/atoms/ALogo.vue')['default']
    AsideNavbar: typeof import('./src/components/AsideNavbar.vue')['default']
    Avatar: typeof import('./src/components/atoms/Avatar.vue')['default']
    ButtonIcon: typeof import('./src/components/atoms/ButtonIcon.vue')['default']
    CardUser: typeof import('./src/components/molecules/CardUser.vue')['default']
    Logo: typeof import('./src/components/atoms/Logo.vue')['default']
    MCardChat: typeof import('./src/components/molecules/MCardChat.vue')['default']
    MCardUser: typeof import('./src/components/molecules/MCardUser.vue')['default']
    MModalProfile: typeof import('./src/components/molecules/MModalProfile.vue')['default']
    ModalCreateGroupChannel: typeof import('./src/components/ModalCreateGroupChannel.vue')['default']
    ModalLeaveGame: typeof import('./src/components/ModalLeaveGame.vue')['default']
    ModalProfile: typeof import('./src/components/molecules/ModalProfile.vue')['default']
    ModalWelcome: typeof import('./src/components/ModalWelcome.vue')['default']
    MTabSelectUsers: typeof import('./src/components/molecules/MTabSelectUsers.vue')['default']
    OtpInput: typeof import('./src/components/OtpInput.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TabSelectUsers: typeof import('./src/components/molecules/TabSelectUsers.vue')['default']
  }
}
