/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AAvatar: typeof import('./src/components/atoms/AAvatar.vue')['default']
    ABagde: typeof import('./src/components/atoms/ABagde.vue')['default']
    AButton: typeof import('./src/components/atoms/AButton.vue')['default']
    AChatImage: typeof import('./src/components/atoms/AChatImage.vue')['default']
    AlertNotification: typeof import('./src/components/AlertNotification.vue')['default']
    ALogo: typeof import('./src/components/atoms/ALogo.vue')['default']
    AsideNavbar: typeof import('./src/components/AsideNavbar.vue')['default']
    ATextArea: typeof import('./src/components/atoms/ATextArea.vue')['default']
    MCardChat: typeof import('./src/components/molecules/MCardChat.vue')['default']
    MCardUser: typeof import('./src/components/molecules/MCardUser.vue')['default']
    MDropDownChat: typeof import('./src/components/molecules/MDropDownChat.vue')['default']
    MModalBans: typeof import('./src/components/molecules/MModalBans.vue')['default']
    MModalProfile: typeof import('./src/components/molecules/MModalProfile.vue')['default']
    MModalSearch: typeof import('./src/components/molecules/MModalSearch.vue')['default']
    MModalSetChannelPassword: typeof import('./src/components/molecules/MModalSetChannelPassword.vue')['default']
    ModalCreateGroupChannel: typeof import('./src/components/ModalCreateGroupChannel.vue')['default']
    ModalLeaveGame: typeof import('./src/components/ModalLeaveGame.vue')['default']
    ModalWelcome: typeof import('./src/components/ModalWelcome.vue')['default']
    MTabSelectUsers: typeof import('./src/components/molecules/MTabSelectUsers.vue')['default']
    ODetailChat: typeof import('./src/components/organisms/ODetailChat.vue')['default']
    OGameCanvas: typeof import('./src/components/organisms/OGameCanvas.vue')['default']
    OListChatMessages: typeof import('./src/components/organisms/OListChatMessages.vue')['default']
    OListChatUsers: typeof import('./src/components/organisms/OListChatUsers.vue')['default']
    OtpInput: typeof import('./src/components/OtpInput.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
