import { addIcons } from "oh-vue-icons";

import {
  IoGameController,
  IoChatbubblesSharp,
  RiPingPongFill,
  MdKeyboarddoublearrowleft,
  MdWorkhistoryRound,
  MdLogout,
  MdPerson,
  MdSunny,
  MdModenight,
  MdSettings,
  Si42,
  MdBlock,
  MdModeedit,
  MdInfoRound,
  MdSupervisoraccount,
  MdModeeditTwotone,
  GiBananaBunch,
  MdEmail,
  FaHamburger,
  GiPingPongBat,
  MdCrisisalert,
} from "oh-vue-icons/icons";

addIcons(
  MdSettings,
  MdPerson,
  MdLogout,
  IoGameController,
  IoChatbubblesSharp,
  RiPingPongFill,
  MdWorkhistoryRound,
  MdKeyboarddoublearrowleft,
  MdModenight,
  MdSunny,
  Si42,
  MdBlock,
  MdModeedit,
  MdInfoRound,
  MdSupervisoraccount,
  MdModeeditTwotone,
  GiBananaBunch,
  MdEmail,
  FaHamburger,
  GiPingPongBat,
  MdCrisisalert
);
