import { addIcons } from "oh-vue-icons";

import {
  GiPingPongBat,
  MdAdminpanelsettings,
  MdBlock,
  MdCrisisalert,
  MdEmail,
  MdGroupsSharp,
  MdInfoRound,
  MdKeyboarddoublearrowleft,
  MdLogout,
  MdMessage,
  MdModeedit,
  MdModeeditTwotone,
  MdModenight,
  MdPerson,
  MdPersonaddalt1,
  MdSearch,
  MdSettings,
  MdSunny,
  MdSupervisoraccount,
  MdVideogameasset,
  MdWorkhistoryRound,
  Si42,
} from "oh-vue-icons/icons";

addIcons(
  MdAdminpanelsettings,
  MdPersonaddalt1,
  MdSettings,
  MdPerson,
  MdLogout,
  MdSearch,
  MdVideogameasset,
  MdMessage,
  MdGroupsSharp,
  MdWorkhistoryRound,
  MdKeyboarddoublearrowleft,
  MdModenight,
  MdSunny,
  Si42,
  MdBlock,
  MdModeedit,
  MdInfoRound,
  MdSupervisoraccount,
  MdModeeditTwotone,
  MdEmail,
  GiPingPongBat,
  MdCrisisalert,
);
