import { addIcons } from "oh-vue-icons";

import {
  BiWind,
  GiPingPongBat,
  MdAdminpanelsettings,
  MdBlock,
  MdCrisisalert,
  MdEmail,
  MdGroupsSharp,
  MdInfoRound,
  MdKeyboarddoublearrowleft,
  MdLogout,
  MdMessage,
  MdModeedit,
  MdModeeditTwotone,
  MdModenight,
  MdPerson,
  MdPersonaddalt1,
  MdSearch,
  MdSettings,
  MdSunny,
  MdSupervisoraccount,
  MdVideogameasset,
  MdVolumeoffRound,
  MdVolumeupRound,
  MdWorkhistoryRound,
  Si42,
} from "oh-vue-icons/icons";

addIcons(
  BiWind,
  GiPingPongBat,
  MdAdminpanelsettings,
  MdBlock,
  MdCrisisalert,
  MdEmail,
  MdGroupsSharp,
  MdInfoRound,
  MdKeyboarddoublearrowleft,
  MdLogout,
  MdMessage,
  MdModeedit,
  MdModeeditTwotone,
  MdModenight,
  MdPerson,
  MdPersonaddalt1,
  MdSearch,
  MdSettings,
  MdSunny,
  MdSupervisoraccount,
  MdVideogameasset,
  MdVolumeoffRound,
  MdVolumeupRound,
  MdWorkhistoryRound,
  Si42,
);
